[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "federated-scvi-flower"
version = "1.0.0"
description = "A federated learning example for scvi-tools using Flower"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.9.0",
    "scvi-tools>=1.1.2",
    "scanpy>=1.9.8",
    "torch>=2.1.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "anndata>=0.9.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "tommaso-sommaruga"

[tool.flwr.app.components]
serverapp = "federated_scvi_flower.server_scvi:app"
clientapp = "federated_scvi_flower.client_scvi:app"

[tool.flwr.app.config]
# Defines the number of clients to simulate.
num_clients = 3
num_rounds = 3
local-epochs = 3
hvg_list_path = "data/hvg_list.json"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 3
