[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "federated-scvi-flower"
version = "1.0.0"
description = "A federated learning example for scvi-tools using Flower"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.9.0",
    "scvi-tools>=1.1.2",
    "scanpy>=1.9.8",
    "torch>=2.1.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "anndata>=0.9.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "tommaso-sommaruga"

[tool.flwr.app.components]
serverapp = "app.server_scvi:app"
clientapp = "app.client_scvi:app"

[tool.flwr.app.config]
# Defines the number of clients to simulate.
num_clients = 3
num_rounds = 20
local-epochs = 5
hvg_list_path = "0_data/hvg_list.json"
batch_list_path = "0_data/batch_list.json"
adata_test_path = "0_data/pancreas_test.h5ad"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 3
